version: "3"
services: 

    server:
        build:
            context: ./server
            dockerfile: Dockerfile 
        ports:
            - 8000:8000
        volumes:
            - ./server:/server
        depends_on: 
            - db
        command: >
            bash -c '
            python manage.py runserver 0:8000'
            # 'python manage.py makemigrations &&
            # python manage.py migrate'
    
    db:
        image: postgres:latest
        ports:
            - 5433:5432
        environment: 
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres