# Generated by Django 3.0.8 on 2021-07-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_profile_endsurveytime'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mod_order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
