# Generated by Django 3.0.8 on 2021-07-27 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_selectedsuggestion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersuggestion',
            old_name='cat_text',
            new_name='suggested_cat',
        ),
        migrations.RenameField(
            model_name='usersuggestion',
            old_name='subcat_text',
            new_name='suggested_subcat',
        ),
    ]
