# Generated by Django 3.0.8 on 2021-07-27 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210727_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersuggestion',
            name='doctype',
        ),
        migrations.RemoveField(
            model_name='usersuggestion',
            name='suggested_cat',
        ),
    ]
