# Generated by Django 3.0.8 on 2021-07-27 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210727_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersuggestion',
            name='suggested_subcat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
