# Generated by Django 3.0.8 on 2021-07-28 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210727_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='consent_agreed',
        ),
    ]
