# Generated by Django 3.0.8 on 2021-08-14 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0016_auto_20210804_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedSuggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_reviewed', models.BooleanField(default=False)),
                ('is_similar', models.BooleanField(blank=True, null=True)),
                ('mine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.UserSuggestion')),
            ],
        ),
        migrations.RemoveField(
            model_name='selectedsuggestion',
            name='is_grouped',
        ),
        migrations.DeleteModel(
            name='GroupLink',
        ),
        migrations.AddField(
            model_name='assignedsuggestion',
            name='others',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SelectedSuggestion'),
        ),
        migrations.AddField(
            model_name='assignedsuggestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
