# Generated by Django 3.0.8 on 2021-08-16 03:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0017_auto_20210814_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignedsuggestion',
            old_name='mine',
            new_name='my_suggestion',
        ),
        migrations.RemoveField(
            model_name='assignedsuggestion',
            name='is_similar',
        ),
        migrations.CreateModel(
            name='Similarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_similar', models.BooleanField(default=False)),
                ('mine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mine', to='api.SelectedSuggestion')),
                ('others', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='others', to='api.SelectedSuggestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
