# Generated by Django 3.0.8 on 2021-07-29 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0014_remove_profile_consent_agreed'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_text', models.CharField(max_length=225)),
                ('subcat_text', models.CharField(max_length=225)),
                ('doctype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.DocType')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TargetBoxAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annot_type', models.CharField(max_length=255)),
                ('suggested_subcat', models.CharField(blank=True, max_length=255, null=True)),
                ('box_id', models.IntegerField(blank=True, default=999, null=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('annotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Annotation')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.InitCat')),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Document')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_users', to=settings.AUTH_USER_MODEL)),
                ('subcat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.InitSubCat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RevisedAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_id', models.IntegerField(blank=True, default=999, null=True)),
                ('revision_type', models.CharField(max_length=225)),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Document')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('label', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.FinalLabel')),
            ],
        ),
        migrations.CreateModel(
            name='RawAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_id', models.IntegerField(blank=True, default=999, null=True)),
                ('has_suggestion', models.BooleanField(default=False)),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Document')),
                ('subcat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.InitSubCat')),
            ],
        ),
        migrations.CreateModel(
            name='BoxAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annot_type', models.CharField(max_length=255)),
                ('suggested_subcat', models.CharField(blank=True, max_length=255, null=True)),
                ('box_id', models.IntegerField(blank=True, default=999, null=True)),
                ('annotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Annotation')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.InitCat')),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Document')),
                ('subcat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.InitSubCat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
