# Generated by Django 3.0.8 on 2021-08-14 13:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20210814_1338'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TargetBoxAnnotation',
            new_name='TargetAnnotation',
        ),
    ]
