# Generated by Django 3.0.8 on 2021-08-24 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210814_1338'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BoxAnnotation',
        ),
    ]
