# Generated by Django 3.0.8 on 2021-08-24 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_boxannotation_finalsuggestion_groupedannotation_simscore'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0003_delete_boxannotation'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_text', models.CharField(max_length=255)),
                ('doctype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.DocType')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinalSubCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcat_text', models.CharField(max_length=255)),
                ('subcat_description', models.CharField(max_length=255)),
                ('finalcat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.FinalCat')),
            ],
        ),
        migrations.CreateModel(
            name='RawBoxAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_id', models.IntegerField(default=999)),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Document')),
                ('initcat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.InitCat')),
                ('initsubcat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.InitSubCat')),
            ],
        ),
        migrations.CreateModel(
            name='RevisedBoxAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_id', models.IntegerField(default=999)),
                ('revision_type', models.CharField(max_length=225)),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Document')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('finalcat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.FinalCat')),
                ('finalsubcat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.FinalSubCat')),
            ],
        ),
        migrations.RemoveField(
            model_name='revisedannotation',
            name='box_id',
        ),
        migrations.RemoveField(
            model_name='revisedannotation',
            name='document',
        ),
        migrations.RemoveField(
            model_name='revisedannotation',
            name='label',
        ),
        migrations.RemoveField(
            model_name='targetannotation',
            name='annot_type',
        ),
        migrations.RemoveField(
            model_name='targetannotation',
            name='box_id',
        ),
        migrations.RemoveField(
            model_name='targetannotation',
            name='cat',
        ),
        migrations.RemoveField(
            model_name='targetannotation',
            name='document',
        ),
        migrations.RemoveField(
            model_name='targetannotation',
            name='subcat',
        ),
        migrations.RemoveField(
            model_name='targetannotation',
            name='suggested_subcat',
        ),
        migrations.RemoveField(
            model_name='targetannotation',
            name='user',
        ),
        migrations.AddField(
            model_name='revisedannotation',
            name='annotation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.GroupedAnnotation'),
        ),
        migrations.AddField(
            model_name='targetannotation',
            name='doctype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.DocType'),
        ),
        migrations.AlterField(
            model_name='targetannotation',
            name='annotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.GroupedAnnotation'),
        ),
        migrations.DeleteModel(
            name='RawAnnotation',
        ),
        migrations.AddField(
            model_name='revisedannotation',
            name='finalcat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.FinalCat'),
        ),
        migrations.AddField(
            model_name='revisedannotation',
            name='finalsubcat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.FinalSubCat'),
        ),
    ]
